name: Sync Issues to JIRA

on:
  issues:
    types: [opened, reopened, closed]

jobs:
  update:
    name: Update Issue
    uses: canonical/sdcore-github-workflows/.github/workflows/issues.yaml@main
<<<<<<< HEAD
    secrets: inherit
=======
    secrets:
      JIRA_URL: ${{ secrets.JIRA_URL }}
>>>>>>> a699fea (Adds issues workflow)
